l_english:
# __0 - title, ___1 - desc, others are options
# §G____§! - green text §R____§! - red text §Y____§! - yellow text

#decision:
 pte_game_options_title: "²þ¬ª Ðƒ °¡°°"
 pte_game_options_desc: ""

#general
 pte_settings.10: "²þ¬ª Ðƒ °¡°°"
 pte_settings.11: "ƒ¡ ±¨®¢²¿ ¢ ÐŒª°°º ª°º ƒ¥¢º °¡°°.\n…¦¿ ¢º ¯¨² ¢¬®½¶²¿/²¬®½¶²¿ ©°º casus belli ª/ª®ª ¯ª°º ¦¥¢º ± ¢¯³ ³¯²°ª½.\n\n‰¯²º ¡º²ªþ ®ª¡ ¢¬®½¶²/²¬®½¶² ±¦®°°³½ ¯°ª¬³ ¯¦, ®ª¡ ²¬½² ¯°½ °²¬ ¥³±±º ¯°ª¬.\n‰¦¬©¬ª ±¬¨³², ¢¬®½¶° ®ª ¯°ª¬."
 pte_settings.12: "‚²¢, ¢°³²¿¾ ¬ ª¥"
 pte_settings.13: "‰¢ª²¿ ª ¢¬®½¶ª²¿/¢º¬®½¶ª²¿ ¢ °²þ¬ª"
 pte_settings.14: "ª°º ¦¥¢º ³¢®ª¶°ª¾/³¯°¿Œ°ª¾ ¯°¦²"
 pte_settings.15: "†°´°®¿°¾ †¯±ª¾ °¡°°"
 pte_settings.16: "ª°º ¦¥¢º ¡¯° ¬²¯ª"
 
 pte_all_enabled_tt: "Ï ¯°ª¬ª ÐŒª°°º ª°º ƒ¥¢¢ °¡°° §G¢¬®½¶°º§!!\n¨¯ª², ¶²¡º ¢º¬®½¶ª²¿ ¢ž."
 pte_all_disabled_tt: "Ï ¯°ª¬ª ÐŒª°°º ª°º ƒ¥¢¢ °¡°° §R²¬®½¶°º§!!\n¨¯ª², ¶²¡º ¢¬®½¶ª²¿ ¢ž."
 pte_partially_enabled_tt: "°ª¬ª ÐŒª°°º ª°º ƒ¥¢¢ °¡°° §Y¶²ª¶° ¢¬®½¶°º§!!\n¨¯ª², ¶²¡º ¢º¬®½¶ª²¿ ¢ž."
 pte_mandate_enabled_tt: "ª°º ¦¥¢º §Y‹ª®°ª¾/Ô¬³Œ°ª¾ ¯²°ª¶²¢§! §G¢¬®½¶°º§!."
 pte_mandate_disabled_tt: "ª°º ¦¥¢º §Y‹ª®°ª¾/Ô¬³Œ°ª¾ ¯²°ª¶²¢§! §R²¬®½¶°º§!."
 pte_infernal_enabled_tt: "Ðƒ ¯°ª¬ ¯°º ´ªµª®¿°þ ®ª¥ªª †¯±ªª °¡°° ° †°´°®¿°ºþ ƒ¢ §G¢¬®½¶°§!."
 pte_infernal_disabled_tt: "Ðƒ ¯°ª¬ ¯°º ´ªµª®¿°þ ®ª¥ªª †¯±ªª °¡°° ° †°´°®¿°ºþ ƒ¢ §R²¬®½¶°§!."
 pte_map_enabled_tt: "ª°º ¦¥¢º §Y¡¯° ¬²§! §G¢¬®½¶°º§!."
 pte_map_disabled_tt: "ª°º ¦¥¢º §Y¡¯° ¬²§! §R²¬®½¶°º§!."
 
#dynastic
 pte_settings.20: "ƒª°²ª¾"
 pte_settings.21: "™² ¥³±± ¦¨ª²:\n       ª®¿° ©¢²ª °Œ¥ ±¢ª²®¾  ¬°²¯ ª© ¢¨¬þ ²°º.\n       ª®¿° ©¢²ª ¢¨¬¥ ±¢ª²®¾  ¬°²¯ ª© °Œþ ²°º.\n       ‹²ª²¿ °ª®¿²¢°°ºþ ¦ª°²ª¶¬ªþ ¡¬ ¯¨¦³ °¯ª ª ¢¥¯.\n       ƒ®¥ª²ª¯ª©ª¢²¿ ¦ª°²ª¶¬³½ ¢²¢¿.\n       ‰²¡¢²¿ ¦ª°²ª¶¬þ ®¥ª²ª¯ª©µªª."
 pte_settings.22: "Ï°³²¿¾ ¬ ¥®¢°¯³ ¯°½ ¯¦"
 pte_settings.23: "ª®¿²¢°°º ©¢¦º"
 pte_settings.24: "ª®¿²¢°°ºþ ¦ª°²ª¶¬ªþ ¡¬"
 pte_settings.25: "‰ª°³¦ª²®¿°¾ (¦-)®¥ª²ª¯ª©µª¾"
 
 pte_divorce_enabled_tt: "ª°º ¦¥¢º §Yª®¿²¢°°¥ Ð©¢¦§! §G¢¬®½¶°º§!."
 pte_divorce_disabled_tt: "ª°º ¦¥¢º §Yª®¿²¢°°¥ Ð©¢¦§! §R²¬®½¶°º§!."
 pte_marriage_enabled_tt: "ª°ºþ ¦¥¢ §Yª®¿²¢°°¥ €¬§! §G¢¬®½¶ž°§!."
 pte_marriage_disabled_tt: "ª°ºþ ¦¥¢ §Yª®¿²¢°°¥ €¬§! §R²¬®½¶ž°§!."
 pte_legitimize_enabled_tt: "ª°º ¦¥¢º §YÙ¡¢°ª¾ ƒª°²ª¶¬þ ˆ¥ª²ª¯ª©µªª§! ª §Yƒ®¥ª²ª¯ª©ªµªª ¦ª°²ª¶¬þ ¢²¢ª§! §G¢¬®½¶°º§!."
 pte_legitimize_disabled_tt: "ª°º ¦¥¢º §YÙ¡¢°ª¾ ƒª°²ª¶¬þ ˆ¥ª²ª¯ª©µªª§! ª §Yƒ®¥ª²ª¯ª©ªµªª ¦ª°²ª¶¬þ ¢²¢ª§! §R²¬®½¶°º§!."
 
#hegemony
 pte_settings.30: "‚¥¯°ª¾"
 pte_settings.31: "™² ¥³±± ¦¨ª²:\n       ÔB ¦®¾ ¼¬°¯ª¶¬ª/¢°°-¯¬ª/¢°°º ¥¥¯°¢ ª ª ³°ª¬®¿°º ¯ª°º ¦¥¢º.\n       ª°ºþ ¦¥¢ ¦®¾ ²¬© ¢¥ ² ¬³®¿²³°þ ¥¥¯°ªª.\n       CB ª ¯ª°ºþ ¦¥¢ ¦®¾ ±¢² ¢¨¬þ ¬³®¿²³°þ ¥¥¯°ªª ¦®¾ ¢Œþ ¬³®¿²³°þ ¥³±±º"
 pte_settings.32: "™¬°¯ª¶¬ªþ ¥¥¯°"
 pte_settings.33: "Ï°°-¯¬þ ¥¥¯°"
 pte_settings.34: "Ï°°ºþ ¥¥¯°"
 pte_settings.35: "²¬© ² ¬³®¿²³°þ ¥¥¯°ªª"
 pte_settings.36: "‰¢²ª²¿ ¬³®¿²³°³½ ¥¥¯°ª½"
 pte_settings.37: "µª°®ª©¯ ¦®¾ ¬³®¿²³°¥ ¥¥¯°"
 
 pte_ecoheg_enabled_tt: "ª°ºþ ¦¥¢ §Y‰ª°³¨¦°ª¾ ¬ €°¬²²¢³§! ª CB §Y™¬°¯ª¶¬¾ ‚¥¯°ª¾§! §G¢¬®½¶°º§!."
 pte_ecoheg_disabled_tt: "ª°ºþ ¦¥¢ §Y‰ª°³¨¦°ª¾ ¬ €°¬²²¢³§! ª CB §Y™¬°¯ª¶¬¾ ‚¥¯°ª¾§! §R²¬®½¶°º§!."
 pte_navheg_enabled_tt: "ª°ºþ ¦¥¢ §Y…¢² ´®²§! ª CB §YÏ°°-¯¬¾ ‚¥¯°ª¾§! §G¢¬®½¶°º§!."
 pte_navheg_disabled_tt: "ª°ºþ ¦¥¢ §Y…¢² ´®²§! ª CB §YÏ°°-¯¬¾ ‚¥¯°ª¾§! §R²¬®½¶°º§!."
 pte_milheg_enabled_tt: "ª°ºþ ¦¥¢ §Yƒ¯°²µªª Ï°°¥ ‰¢¦²¢§! ª CB §YÏ°°¾ ‚¥¯°ª¾§! §G¢¬®½¶°º§!."
 pte_milheg_disabled_tt: "ª°ºþ ¦¥¢ §Yƒ¯°²µªª Ï°°¥ ‰¢¦²¢§! ª CB §YÏ°°¾ ‚¥¯°ª¾§! §R²¬®½¶°º§!."
 pte_culhegA_enabled_tt: "ª°ºþ ¦¥¢ §Y²¬© ² ³®¿²³°þ ‚¥¯°ªª§! §G¢¬®½¶ž°§!."
 pte_culhegA_disabled_tt: "ª°ºþ ¦¥¢ §Y²¬© ² ³®¿²³°þ ‚¥¯°ªª§! §R²¬®½¶ž°§!."
 pte_culhegB_enabled_tt: "ª°ºþ ¦¥¢ §Y‰²°©ªþ ° ³®¿²³°³½ ‚¥¯°ª½§! ª CB §Y‰²°©ª¾ ° ³®¿²³°³½ ‚¥¯°ª½§! §G¢¬®½¶°º§!."
 pte_culhegB_disabled_tt: "ª°ºþ ¦¥¢ §Y‰²°©ªþ ° ³®¿²³°³½ ‚¥¯°ª½§! ª CB §Y‰²°©ª¾ ° ³®¿²³°³½ ‚¥¯°ª½§! §R²¬®½¶°º§!."
 pte_culheg_nation_enabled_tt: "¦ª´ªµª¢°°ºþ CB §Yµª°®ª©¯§! ¦®¾ §Y³®¿²³°¥ ‚¥¯°§! §G¢¬®½¶ž°§!."
 pte_culheg_nation_disabled_tt: "¦ª´ªµª¢°°ºþ CB §Yµª°®ª©¯§! ¦®¾ §Y³®¿²³°¥ ‚¥¯°§! §R²¬®½¶ž°§!."
 
#religious
 pte_settings.40: "Ð®ª¥ª¾"
 pte_settings.41: "™² ¥³±± ¦¨ª²:\n       CB ª ¯ª°ºþ ¦¥¢ ¦®¾ °¾²ª¾ ²®³¶°ª¾  ¢Œþ ²°º.\n       ª°ºþ ¦¥¢ ¦®¾ ¯°º Ï¢°¥ Ð¬² ° ¢Œ¥ ¬°¦ª¦².\n       ª°ºþ ¦¥¢ ¦®¾ ¥¡¨ ¬¢ª¸°ªµº Ï¢°¥ Ð¬²².\n       CB ª ¯ª°ºþ ¦¥¢ ¦®¾ ©¯¦®°ª¾ ¯°º ¬°´ªª ±¢ª°µªþ ¢¥¯  ¢Œþ ¢º ° ¥ ¢³.\n       ª°ºþ ¦¥¢ ¦®¾ ©¦°ª¾ ¡¥ µ°² ´¯µªª ¢Œþ ¢º ¢ ¢¨¬þ ²®ªµ.\n       ª°ºþ ¦¥¢ ¦®¾ ±ª¸°ª¾ ¢¨¬¥ ¢¦ª¬®.\n       ª°ºþ ¦¥¢ ¦®¾ ©¢² ²ª²³® \"…¸ª²°ª¬ Ïº\"."
 pte_settings.42: "Ô°¾²¿ ²®³¶°ª"
 pte_settings.43: "‹²°¢ª²¿ °²ª¬²"
 pte_settings.44: "Ð©¥¡ª²¿ Ô¬¢ª¸°ªµ³ Ð¬²²"
 pte_settings.45: "…¸ª²ª²¿ €²¿¢ ± Ï"
 pte_settings.46: "Ð±²°ª²¿ †²ª°°³½ Ï³"
 pte_settings.47: "‰ª²ª²¿ Ï¦ª¬®"
 pte_settings.48: "‰²°©ªª ° …¸ª²°ª¬ Ïº"
 
 pte_excom_enabled_tt: "ª°ºþ ¦¥¢ §YÔ°¾²ª¾ ²®³¶°ª¾§! §G¢¬®½¶ž°§!."
 pte_excom_disabled_tt: "ª°ºþ ¦¥¢ §YÔ°¾²ª¾ ²®³¶°ª¾§! §R²¬®½¶ž°§!."
 pte_antipope_enabled_tt: "ª°ºþ ¦¥¢ §Y‹²°¢®°ª¾ °²ª¬²§! §G¢¬®½¶ž°§!."
 pte_antipope_disabled_tt: "ª°ºþ ¦¥¢ §Y‹²°¢®°ª¾ °²ª¬²§! §R²¬®½¶ž°§!."
 pte_curia_enabled_tt: "ª°ºþ ¦¥¢ §Y‚¡¨ Ô¬¢ª¸°ªµº Ð¬²²§! §G¢¬®½¶ž°§!."
 pte_curia_disabled_tt: "ª°ºþ ¦¥¢ §Y‚¡¨ Ô¬¢ª¸°ªµº Ð¬²²§! §R²¬®½¶ž°§!."
 pte_bretheren_enabled_tt: "CB §Y…¸ª²ª²¿ €²¿¢ ± Ï§! ª ²¢²²¢³½¸ªþ ¯ª°ºþ ¦¥¢ §G¢¬®½¶°º§!."
 pte_bretheren_disabled_tt: "CB §Y…¸ª²ª²¿ €²¿¢ ± Ï§! ª ²¢²²¢³½¸ªþ ¯ª°ºþ ¦¥¢ §R²¬®½¶°º§!."
 pte_spawncenter_enabled_tt: "ª°ºþ ¦¥¢ §YÐ±²°°ª¾ †²ª°°þ Ïº§! §G¢¬®½¶ž°§!."
 pte_spawncenter_disabled_tt: "ª°ºþ ¦¥¢ §YÐ±²°°ª¾ †²ª°°þ Ïº§! §R²¬®½¶ž°§!."
 pte_cardinal_enabled_tt: "ª°ºþ ¦¥¢ §Y‰ª¸°ª¾ Ï¦ª¬®§! §G¢¬®½¶ž°§!."
 pte_cardinal_disabled_tt: "ª°ºþ ¦¥¢ §Y‰ª¸°ª¾ Ï¦ª¬®§! §R²¬®½¶ž°§!."
 pte_dof_enabled_tt: "ª°ºþ ¦¥¢ §Y‰²°©ªþ ° …¸ª²°ª¬ Ïº§! §G¢¬®½¶ž°§!."
 pte_dof_disabled_tt: "ª°ºþ ¦¥¢ §Y‰²°©ªþ ° …¸ª²°ª¬ Ïº§! §R²¬®½¶ž°§!."
 
#economy
 pte_settings.50: "™¬°¯ª¬"
 pte_settings.51: "™² ¥³±± ¦¨ª²:\n       CB ª ¯ª°ºþ ¦¥¢ ¦®¾ ©±² ¡²¢ ¢ ¢¨¬þ ²°.\n       ª°ºþ ¦¥¢ ¦®¾ ³¯°¿Œ°ª¾ ²¡ª®¿°²ª ª ¯°º ¢ ¢¨¬þ ²°  ±ª²¯ ¦ª±®¯²ª¶¬¥ ¢ ¦®¾ ¢.\n       ª°ºþ ¦¥¢ ¦®¾ ©¢² ¯¬°²ª®ª©¯ ³ ±°ª¬.\n       ª°ºþ ¦¥¢ ¦®¾ ±ª°³¨¦°ª¾ ¢¥ ¬ ¢²³±®°ª½ ¢ ¢Œ³ ²¥¢³½ ®ª¥³.\n       ª°ºþ ¦¥¢ ¦®¾ ©¢² ¯¬°²ª®ª©¯ ¢ ²¥¢º ¢þ°.\n       ª°ºþ ¦¥¢ ¦®¾ ±®³¶°ª¾ ²¥¢¥ ¢®ª¾°ª¾ ¢ ¦¯Œ°¯ ²¥¢¯ ³©® ¢¥.\n       ª°ºþ ¦¥¢ ¦®¾ ³¯°¿Œ°ª¾ ¢®ª¶ª¾ ¢¥ ª ±®³¶°ª¾ ±²ª¨."
 pte_settings.52: "…±²ª²¿ ¡²¢"
 pte_settings.53: "ƒ²¡ª®ª©ª¢²¿ °µª½"
 pte_settings.54: "‰ª°³¦ª²®¿° ¼¯¡¥"
 pte_settings.55: "‰ª¦ª°°ª ¬ ²¥¢þ ®ª¥"
 pte_settings.56: "…¢² ¯¬°²ª®ª©¯"
 pte_settings.57: "¢°ºþ ¦¥¢"
 pte_settings.58: "Ð©¥¡ª²¿ Ï®ª¶²¢°°ºþ ¦¢"
 
 pte_ban_slave_enabled_tt: "CB §Y…±²ª²¿ Ð¡²¢§! ª ²¢²²¢³½¸ªþ ¯ª°ºþ ¦¥¢ §G¢¬®½¶°º§!."
 pte_ban_slave_disabled_tt: "CB §Y…±²ª²¿ Ð¡²¢§! ª ²¢²²¢³½¸ªþ ¯ª°ºþ ¦¥¢ §R²¬®½¶°º§!."
 pte_destabilize_enabled_tt: "ª°ºþ ¦¥¢ §Yƒ²¡ª®ª©µªª °µªª§! §G¢¬®½¶ž°§!."
 pte_destabilize_disabled_tt: "ª°ºþ ¦¥¢ §Yƒ²¡ª®ª©µªª °µªª§! §R²¬®½¶ž°§!."
 pte_embargo_enabled_tt: "ª°ºþ ¦¥¢ §Y‰ª°³¦ª²®¿°¥ ™¯¡¥§! §G¢¬®½¶ž°§!."
 pte_embargo_disabled_tt: "ª°ºþ ¦¥¢ §Y‰ª°³¦ª²®¿°¥ ™¯¡¥§! §R²¬®½¶ž°§!."
 pte_trade_league_enabled_tt: "ª°ºþ ¦¥¢ §Y‰ª¦ª°°ª¾ ¬ ²¥¢þ ®ª¥§! §G¢¬®½¶ž°§!."
 pte_trade_league_disabled_tt: "ª°ºþ ¦¥¢ §Y‰ª¦ª°°ª¾ ¬ ²¥¢þ ®ª¥§! §R²¬®½¶ž°§!."
 pte_mercantilism_enabled_tt: "ª°ºþ ¦¥¢ §Y…¢² ¯¬°²ª®ª©¯§! §G¢¬®½¶ž°§!."
 pte_mercantilism_disabled_tt: "ª°ºþ ¦¥¢ §Y…¢² ¯¬°²ª®ª©¯§! §R²¬®½¶ž°§!."
 pte_unequal_treaty_enabled_tt: "ª° ¥®Œ°ª §Y¢°¥ ¦¥¢§! §G¢¬®½¶ž°§!."
 pte_unequal_treaty_disabled_tt: "ª°ºþ ¥®Œ°ª §Y¢°¥ ¦¥¢§! §R²¬®½¶ž°§!."
 pte_raid_court_enabled_tt: "ª°ºþ ¦¥¢ §Y‚¡¨ Ï®ª¶²¢°°¥ ¦¢§! §G¢¬®½¶ž°§!."
 pte_raid_court_disabled_tt: "ª°ºþ ¦¥¢ §Y‚¡¨ Ï®ª¶²¢°°¥ ¦¢§! §R²¬®½¶ž°§!."
 
#militare
 pte_settings.60: "Ïþ¬"
 pte_settings.61: "™² ¥³±± ¦¨ª²:\n       CB ª ¯ª°ºþ ¦¥¢ ¦®¾ ©±² ¡²¢ ¢ ¢¨¬þ ²°.\n       ª°ºþ ¦¥¢ ¦®¾ ³¯°¿Œ°ª¾ ²¡ª®¿°²ª ª ¯°º ¢ ¢¨¬þ ²°  ±ª²¯ ¦ª±®¯²ª¶¬¥ ¢ ¦®¾ ¢.\n       ª°ºþ ¦¥¢ ¦®¾ ©¢² ¯¬°²ª®ª©¯ ³ ±°ª¬.\n       ª°ºþ ¦¥¢ ¦®¾ ±ª°³¨¦°ª¾ ¢¥ ¬ ¢²³±®°ª½ ¢ ¢Œ³ ²¥¢³½ ®ª¥³.\n       ª°ºþ ¦¥¢ ¦®¾ ©¢² ¯¬°²ª®ª©¯ ¢ ²¥¢º ¢þ°.\n       ª°ºþ ¦¥¢ ¦®¾ ±®³¶°ª¾ ²¥¢¥ ¢®ª¾°ª¾ ¢ ¦¯Œ°¯ ²¥¢¯ ³©® ¢¥.\n       ª°ºþ ¦¥¢ ¦®¾ ³¯°¿Œ°ª¾ ¢®ª¶ª¾ ¢¥ ª ±®³¶°ª¾ ±²ª¨."
 pte_settings.62: "Ð©³¨°ª ¯ªª"
 pte_settings.63: "‰²¡¢²¿ ¡¢-®¦²"
 pte_settings.64: "ƒ¯ª®ª²ª©¢²¿ ¥°ªµº"
 pte_settings.65: "Ð©³¨°ª ´®²"
 pte_settings.66: "²°¢ª²¿ ¡¬ª °¡¥ª"
 
 pte_army_disarmament_enabled_tt: "ª°ºþ ¦¥¢ §YÐ©³¨°ª¾ ¯ªª§! §G¢¬®½¶ž°§!."
 pte_army_disarmament_disabled_tt: "ª°ºþ ¦¥¢ §YÐ©³¨°ª¾ ¯ªª§! §R²¬®½¶ž°§!."
 pte_manpower_enabled_tt: "ª°ºþ ¦¥¢ §YÙ¡¢°ª¾ ¡¢-®¦²§! §G¢¬®½¶ž°§!."
 pte_manpower_disabled_tt: "ª°ºþ ¦¥¢ §YÙ¡¢°ª¾ ¡¢-®¦²§! §R²¬®½¶ž°§!."
 pte_demil_border_enabled_tt: "ª°ºþ ¦¥¢ §Yƒ¯ª®ª²ª©µªª ¥°ªµ§! §G¢¬®½¶ž°§!."
 pte_demil_border_disabled_tt: "ª°ºþ ¦¥¢ §Yƒ¯ª®ª²ª©µªª ¥°ªµ§! §R²¬®½¶ž°§!."
 pte_fleet_disarmament_enabled_tt: "ª°ºþ ¦¥¢ §YÐ©³¨°ª¾ ´®²§! §G¢¬®½¶ž°§!."
 pte_fleet_disarmament_disabled_tt: "ª°ºþ ¦¥¢ §YÐ©³¨°ª¾ ´®²§! §R²¬®½¶ž°§!."
 pte_stop_raid_enabled_tt: "ª°ºþ ¦¥¢ §Y²°¢¬ª ¡¬ª °¡¥¢§! §G¢¬®½¶ž°§!."
 pte_stop_raid_disabled_tt: "ª°ºþ ¦¥¢ §Y²°¢¬ª ¡¬ª °¡¥¢§! §R²¬®½¶ž°§!."
 
#tech and knowledge
 pte_settings.70: "Ù°®¥ªª ª †°²ª²³²º"
 pte_settings.71: "™² ¥³±± ¦¨ª²:\n       Ô²°¦²°º ¯ª°º ¦¥¢º ¦®¾ ¬¨ª ²°®¥ªþ ³ ¢¨¬¥ ®ª¦ ¢ ®³¶ ²²¢°ª¾ ² °¥ ° 2 ³¢°¾\n       ª°ºþ ¦¥¢ ¦®¾ ±ª² ±¥ ª°²ª²³² ¢ ¢Œþ ²®ª¶°þ ¡®²ª ¢ ®³¶, ®ª ¼²² ª°²ª²³² ±ª°¾² ¢¥¯\n        CB ¡¥ © ©°°ª¾¯ª, ±©¢®¾½¸ªþ ¬²¿ ²°®¥ªª ª ª°²ª²³²º ¦Œ¢®."
 pte_settings.72: "Ô²°¦²°ºþ ‰ª°³¦ª²®¿°ºþ ¡¯° ²°®¥ª¾¯ª"
 pte_settings.73: "‰ª°³¦ª²®¿°ºþ ¡¯° ©°°ª¾¯ª"
 pte_settings.74: "¡¥ © ©°°ª¾¯ª"
 
 pte_orig_tech_sharing_enabled_tt: "ª°ºþ ¦¥¢ Ô²°¦²°¥ §Y‰ª°³¦ª²®¿°¥ ¡¯° ²°®¥ª¾¯ª§! §G¢¬®½¶ž°§!."
 pte_orig_tech_sharing_disabled_tt: "ª°ºþ ¦¥¢ Ô²°¦²°¥ §Y‰ª°³¦ª²®¿°¥ ¡¯° ²°®¥ª¾¯ª§! §R²¬®½¶ž°§!."
 pte_knowledge_sharing_enabled_tt: "ª°ºþ ¦¥¢ §Y‰ª°³¦ª²®¿°¥ ¡¯° ©°°ª¾¯ª§! §G¢¬®½¶ž°§!."
 pte_knowledge_sharing_disabled_tt: "ª°ºþ ¦¥¢ §Y‰ª°³¦ª²®¿°¥ ¡¯° ©°°ª¾¯ª§! §R²¬®½¶ž°§!."
 pte_raid_knowledge_enabled_tt: "CB §Y¡¥ © ©°°ª¾¯ª§! ª ¢ ²¢²²¢³½¸ª ¯ª°º ¦¥¢º §G¢¬®½¶°º§!."
 pte_raid_knowledge_disabled_tt: "CB §Y¡¥ © ©°°ª¾¯ª§! ª ¢ ²¢²²¢³½¸ª ¯ª°º ¦¥¢º §R²¬®½¶°º§!."
 
#ruler and advisors
 pte_settings.80: "‰¢ª²®¿ ª ¢²°ª¬ª"
 pte_settings.81: "™² ¥³±± ¦¨ª² ¯ª°º ¦¥¢º, ±©¢®¾½¸ª:\n       Ô°ª©ª²¿ °¢º¬ ¢¨¬¥ ±¢ª²®¾ ª ±¢ºª²¿ ¢Œ.\n       ‹¡ª²¿ ¢¨¬¥ ±¢ª²®¾ ª ±®³¶ª²¿ ¯°³, ¢°³½ ¥ °¢º¬¯ x3.\n       ‹¡ª²¿ ¢¨¬¥ ±¢ª²®¾ ª ³¯°¿Œª²¿ ¢Œ ¥®¦.\n       ‰ª²ª²¿ ¢¨¬¥ ¢²°ª¬."
 pte_settings.82: "‰²¡¢²¿ ³±¢®°¶¬³½ ±¯¸¿"
 pte_settings.83: "‰²¡¢²¿ ±±³¬³"
 pte_settings.84: "Ô¹²¿ ±¢ª²®¾"
 pte_settings.85: "‰ª²ª²¿ ¢²°ª¬"
 
 pte_aid_enabled_tt: "ª°º ¦¥¢º §YÙ¡¢°ª¾ ³±¢®°¶¬þ ±¯¸ª§! §G¢¬®½¶°º§!."
 pte_aid_disabled_tt: "ª°º ¦¥¢º §YÙ¡¢°ª¾ ³±¢®°¶¬þ ±¯¸ª§! §R²¬®½¶°º§!."
 pte_seppuku_enabled_tt: "ª°ºþ ¦¥¢ §YÙ¡¢°ª¾ ±±³¬³§! §G¢¬®½¶ž°§!."
 pte_seppuku_disabled_tt: "ª°ºþ ¦¥¢ §YÙ¡¢°ª¾ ±±³¬³§! §R²¬®½¶ž°§!."
 pte_sacrifice_enabled_tt: "ª°ºþ ¦¥¢ §Y‰¨ª°ª¾ ±¢ª²®¾§! §G¢¬®½¶ž°§!."
 pte_sacrifice_disabled_tt: "ª°ºþ ¦¥¢ §Y‰¨ª°ª¾ ±¢ª²®¾§! §R²¬®½¶ž°§!."
 pte_advisor_enabled_tt: "ª°º ¦¥¢º §Y‰ª¸°ª¾ ¢²°ª¬§! §G¢¬®½¶°º§!."
 pte_advisor_disabled_tt: "ª°º ¦¥¢º §Y‰ª¸°ª¾ ¢²°ª¬§! §R²¬®½¶°º§!."
 
#diplomacy
 pte_settings.90: "ƒª±®¯²ª¾"
 pte_settings.91: "™² ¥³±± ¦¨ª² casus bellis, ±©¢®¾½¸ª:\n       Ô°ª©ª²¿ ²ª¯²¿ §Y¢¡¨¦°ª¾ ¢®§!, §Y¢¡¨¦°ª¾ ¦¨¢§!, §YÏ©¢¸°ª¾ °µª°®¿°º ±¢ª°µªþ§!, §Y²¬© ² °µª°®¿°º ±¢ª°µªþ§!.\n       Ô°ª©ª²¿ ²ª¯²¿ ¢°°º ¯ª°º ¦¥¢¢ ª ª±®¿©¢²¿ §Y‰¬© ª®º§! ±²ª¢ ¢¨¬¥ ®ª¦.\n       ¡ ¢ºŒ³¬©°°º ¼´´¬², ¬²º ²¬¨ ¯¥³² ¡º²¿ ª±®¿©¢°º ±²ª¢ ±²ª¢ ®½¡¥ ¶®° ¬®ªµªª, °±¢®°°þ ±²ª¢ ¢.\n       Ô°ª©ª²¿ ²ª¯²¿ §YÙ¡¢°ª¾ ±¢ª°µªª§! ª §Yƒ¯ª®ª²ª©µªª ¥°ªµ§! ±ª ³®¢ªª ©¢² ª¬®½¶ª²®¿° §R‰¥°ª¶°º§! ±¢ª°µªþ."
 pte_settings.92: "¢¡¨¦°ª"
 pte_settings.93: "Ï¯Œ²¿¾ ¢ ¢þ°³ © °©¢ªª¯²¿"
 pte_settings.94: "Ð©¡ª²¿ ¬®ªµª½"
 pte_settings.95: "‰¥°ª¶°º ²°ª¾"
 
 pte_liberation_enabled_tt: "Casus belli §Y¢¡¨¦°ª§! §G¢¬®½¶ž°§!."
 pte_liberation_disabled_tt: "Casus belli §Y¢¡¨¦°ª§! §R²¬®½¶ž°§!."
 pte_rival_subject_enabled_tt: "Casus belli §YÏ¯Œ²¿¾ ¢ ¢þ°³ © °©¢ªª¯²¿§! §G¢¬®½¶ž°§!."
 pte_rival_subject_disabled_tt: "Casus belli §YÏ¯Œ²¿¾ ¢ ¢þ°³ © °©¢ªª¯²¿§! §R²¬®½¶ž°§!."
 pte_anti_coalition_enabled_tt: "Casus belli §YÐ©¡ª²¿ ¬®ªµª½§! §G¢¬®½¶ž°§!."
 pte_anti_coalition_disabled_tt: "Casus belli §YÐ©¡ª²¿ ¬®ªµª½§!  §R²¬®½¶ž°§!."
 pte_border_friction_enabled_tt: "Casus belli §Y‰¥°ª¶°º ²°ª¾§! §G¢¬®½¶ž°§!."
 pte_border_friction_disabled_tt: "Casus belli §Y‰¥°ª¶°º ²°ª¾§! §R²¬®½¶ž°§!."
 
#dlc
 pte_mandate_of_heaven_tt: "§R²³²²¢³² ƒˆÔ:§! §Y°¦² ¡§!"
 pte_emperor_tt: "§R²³²²¢³² ƒˆÔ:§! §Y†¯±²§!"
 pte_el_dorado_tt: "§R²³²²¢³² ƒˆÔ:§! §Y™®¿ ƒ¦§!"
 pte_rights_of_man_tt: "§R²³²²¢³² ƒˆÔ:§! §Y‰¢ Ì®¢¬§!"
 pte_dlc_mare_nostrum_tt: "§R²³²²¢³² ƒˆÔ:§! §Y ²³¯§!"