l_english:
# __0 - title, ___1 - desc, others are options
# §G____§! - green text §R____§! - red text §Y____§! - yellow text

#decision:
 pte_game_options_title: "Настройки РМД Анбеннар"
 pte_game_options_desc: ""

#general
 pte_settings.10: "Настройки РМД Анбеннар"
 pte_settings.11: "Добро пожаловать в Расширенные Мирные Договоры Анбеннар.\nЗдесь вы можете включать/отключать разные casus belli и/или мирные договоры по своему усмотрению.\n\nПараметры событий либо включат/отключат определенную механику мода, либо откроют меню настроек группы механик.\nПодсказки покажут, включена ли механика."
 pte_settings.12: "Готово, вернуться к игре"
 pte_settings.13: "Проверить и включить/выключить все настройки"
 pte_settings.14: "Мирные договоры увеличения/уменьшения мандата"
 pte_settings.15: "Инфернальная Империя Анбеннар"
 pte_settings.16: "Мирные договоры обмена картами"
 
 pte_all_enabled_tt: "Все механики Расширенных Мирных Договоров Анбеннар §Gвключены§!!\nНажмите, чтобы выключить всё."
 pte_all_disabled_tt: "Все механики Расширенных Мирных Договоров Анбеннар §Rотключены§!!\nНажмите, чтобы включить всё."
 pte_partially_enabled_tt: "Механики Расширенных Мирных Договоров Анбеннар §Yчастично включены§!!\nНажмите, чтобы выключить всё."
 pte_mandate_enabled_tt: "Мирные договоры §YУсиления/Сокрушения Наместничества§! §Gвключены§!."
 pte_mandate_disabled_tt: "Мирные договоры §YУсиления/Сокрушения Наместничества§! §Rотключены§!."
 pte_infernal_enabled_tt: "РМД механика смены официальной религии Империи Анбеннар на Инфернальный Двор §Gвключена§!."
 pte_infernal_disabled_tt: "РМД механика смены официальной религии Империи Анбеннар на Инфернальный Двор §Rотключена§!."
 pte_map_enabled_tt: "Мирные договоры §YОбмена карт§! §Gвключены§!."
 pte_map_disabled_tt: "Мирные договоры §YОбмена карт§! §Rотключены§!."
 
#dynastic
 pte_settings.20: "Династия"
 pte_settings.21: "Эта группа содержит:\n       Насильно развести нашего правителя с консортом из вражеской страны.\n       Насильно развести вражеского правителя с консортом из нашей страны.\n       Устроить насильственный династический брак между нами и врагом.\n       Делегитимизировать династическую ветвь.\n       Потребовать династической легитимизации."
 pte_settings.22: "Вернуться к главному меню мода"
 pte_settings.23: "Насильственные разводы"
 pte_settings.24: "Насильственный династический брак"
 pte_settings.25: "Принудительная (де-)легитимизация"
 
 pte_divorce_enabled_tt: "Мирные договоры §YНасильственного Развода§! §Gвключены§!."
 pte_divorce_disabled_tt: "Мирные договоры §YНасильственного Развода§! §Rотключены§!."
 pte_marriage_enabled_tt: "Мирный договор §YНасильственного Брака§! §Gвключён§!."
 pte_marriage_disabled_tt: "Мирный договор §YНасильственного Брака§! §Rотключён§!."
 pte_legitimize_enabled_tt: "Мирные договоры §YТребования Династической Легитимизации§! и §YДелегитимизиции династической ветви§! §Gвключены§!."
 pte_legitimize_disabled_tt: "Мирные договоры §YТребования Династической Легитимизации§! и §YДелегитимизиции династической ветви§! §Rотключены§!."
 
#hegemony
 pte_settings.30: "Гегемония"
 pte_settings.31: "Эта группа содержит:\n       СB для экономических/военно-морских/военных гегемонов и их уникальные мирные договоры.\n       Мирный договор для отказа врага от культурной гегемонии.\n       CB и мирный договор для перехвата вражеской культурной гегемонии для вашей культурной группы"
 pte_settings.32: "Экономический гегемон"
 pte_settings.33: "Военно-морской гегемон"
 pte_settings.34: "Военный гегемон"
 pte_settings.35: "Отказ от культурной гегемонии"
 pte_settings.36: "Перехватить культурную гегемонию"
 pte_settings.37: "Национализм для культурного гегемона"
 
 pte_ecoheg_enabled_tt: "Мирный договор §YПринуждения к Банкротстсву§! и CB §YЭкономическая Гегемония§! §Gвключены§!."
 pte_ecoheg_disabled_tt: "Мирный договор §YПринуждения к Банкротстсву§! и CB §YЭкономическая Гегемония§! §Rотключены§!."
 pte_navheg_enabled_tt: "Мирный договор §YЗахвата флота§! и CB §YВоенно-морская Гегемония§! §Gвключены§!."
 pte_navheg_disabled_tt: "Мирный договор §YЗахвата флота§! и CB §YВоенно-морская Гегемония§! §Rотключены§!."
 pte_milheg_enabled_tt: "Мирный договор §YДемонстрации Военного Превосходства§! и CB §YВоенная Гегемония§! §Gвключены§!."
 pte_milheg_disabled_tt: "Мирный договор §YДемонстрации Военного Превосходства§! и CB §YВоенная Гегемония§! §Rотключены§!."
 pte_culhegA_enabled_tt: "Мирный договор §YОтказа от Культурной Гегемонии§! §Gвключён§!."
 pte_culhegA_disabled_tt: "Мирный договор §YОтказа от Культурной Гегемонии§! §Rотключён§!."
 pte_culhegB_enabled_tt: "Мирный договор §YПретензий на Культурную Гегемонию§! и CB §YПретензия на Культурную Гегемонию§! §Gвключены§!."
 pte_culhegB_disabled_tt: "Мирный договор §YПретензий на Культурную Гегемонию§! и CB §YПретензия на Культурную Гегемонию§! §Rотключены§!."
 pte_culheg_nation_enabled_tt: "Модифицированный CB §YНационализм§! для §YКультурного Гегемона§! §Gвключён§!."
 pte_culheg_nation_disabled_tt: "Модифицированный CB §YНационализм§! для §YКультурного Гегемона§! §Rотключён§!."
 
#religious
 pte_settings.40: "Религия"
 pte_settings.41: "Эта группа содержит:\n       CB и мирный договор для снятия отлучения с вашей страны.\n       Мирный договор для смены Верховного Ректора на вашего кандидата.\n       Мирный договор для грабежа сокровищницы Верховного Ректората.\n       CB и мирный договор для замедления смены конфесии провинций врагом с вашей веры на его веру.\n       Мирный договор для создания особого центра реформации вашей веры во вражеской столице.\n       Мирный договор для похищения вражеского вердикала.\n       Мирный договор для захвата титула \"Защитник Веры\"."
 pte_settings.42: "Снять Отлучение"
 pte_settings.43: "Установить Антиректора"
 pte_settings.44: "Разграбить Сокровищницу Ректората"
 pte_settings.45: "Защитить Братьев по Вере"
 pte_settings.46: "Распространить Истинную Веру"
 pte_settings.47: "Похитить Вердикала"
 pte_settings.48: "Претензии на Защитника Веры"
 
 pte_excom_enabled_tt: "Мирный договор §YСнятия Отлучения§! §Gвключён§!."
 pte_excom_disabled_tt: "Мирный договор §YСнятия Отлучения§! §Rотключён§!."
 pte_antipope_enabled_tt: "Мирный договор §YУстановления Антиректора§! §Gвключён§!."
 pte_antipope_disabled_tt: "Мирный договор §YУстановления Антиректора§! §Rотключён§!."
 pte_curia_enabled_tt: "Мирный договор §YГрабежа Сокровищницы Ректората§! §Gвключён§!."
 pte_curia_disabled_tt: "Мирный договор §YГрабежа Сокровищницы Ректората§! §Rотключён§!."
 pte_bretheren_enabled_tt: "CB §YЗащитить Братьев по Вере§! и соответствующий мирный договор §Gвключены§!."
 pte_bretheren_disabled_tt: "CB §YЗащитить Братьев по Вере§! и соответствующий мирный договор §Rотключены§!."
 pte_spawncenter_enabled_tt: "Мирный договор §YРаспространения Истинной Веры§! §Gвключён§!."
 pte_spawncenter_disabled_tt: "Мирный договор §YРаспространения Истинной Веры§! §Rотключён§!."
 pte_cardinal_enabled_tt: "Мирный договор §YПохищения Вердикала§! §Gвключён§!."
 pte_cardinal_disabled_tt: "Мирный договор §YПохищения Вердикала§! §Rотключён§!."
 pte_dof_enabled_tt: "Мирный договор §YПретензий на Защитника Веры§! §Gвключён§!."
 pte_dof_disabled_tt: "Мирный договор §YПретензий на Защитника Веры§! §Rотключён§!."
 
#economy
 pte_settings.50: "Экономика"
 pte_settings.51: "Эта группа содержит:\n       CB и мирный договор для запрета рабства во вражеской стране.\n       Мирный договор для уменьшения стабильности и маны во вражеской стране с приростом дипломатического веса для вас.\n       Мирный договор для захвата меркантилизма у соперника.\n       Мирный договор для принуждения врага к вступлению в вашу торговую лигу.\n       Мирный договор для захвата меркантилизма в торговых войнах.\n       Мирный договор для получения торгового влияния в домашнем торговом узле врага.\n       Мирный договор для уменьшения величия врага и получения престижа."
 pte_settings.52: "Запретить рабство"
 pte_settings.53: "Дестабилизировать нацию"
 pte_settings.54: "Принудительное эмбарго"
 pte_settings.55: "Присоединение к торговой лиге"
 pte_settings.56: "Захват меркантилизма"
 pte_settings.57: "Неравный договор"
 pte_settings.58: "Разграбить Величественный двор"
 
 pte_ban_slave_enabled_tt: "CB §YЗапретить Рабство§! и соответствующий мирный договор §Gвключены§!."
 pte_ban_slave_disabled_tt: "CB §YЗапретить Рабство§! и соответствующий мирный договор §Rотключены§!."
 pte_destabilize_enabled_tt: "Мирный договор §YДестабилизации нации§! §Gвключён§!."
 pte_destabilize_disabled_tt: "Мирный договор §YДестабилизации нации§! §Rотключён§!."
 pte_embargo_enabled_tt: "Мирный договор §YПринудительного Эмбарго§! §Gвключён§!."
 pte_embargo_disabled_tt: "Мирный договор §YПринудительного Эмбарго§! §Rотключён§!."
 pte_trade_league_enabled_tt: "Мирный договор §YПрисоединения к торговой лиге§! §Gвключён§!."
 pte_trade_league_disabled_tt: "Мирный договор §YПрисоединения к торговой лиге§! §Rотключён§!."
 pte_mercantilism_enabled_tt: "Мирный договор §YЗахвата меркантилизма§! §Gвключён§!."
 pte_mercantilism_disabled_tt: "Мирный договор §YЗахвата меркантилизма§! §Rотключён§!."
 pte_unequal_treaty_enabled_tt: "Мирное соглашение §YНеравного договора§! §Gвключёно§!."
 pte_unequal_treaty_disabled_tt: "Мирный соглашение §YНеравного договора§! §Rотключёно§!."
 pte_raid_court_enabled_tt: "Мирный договор §YГрабежа Величественного двора§! §Gвключён§!."
 pte_raid_court_disabled_tt: "Мирный договор §YГрабежа Величественного двора§! §Rотключён§!."
 
#militare
 pte_settings.60: "Войска"
 pte_settings.61: "Эта группа содержит:\n       CB и мирный договор для запрета рабства во вражеской стране.\n       Мирный договор для уменьшения стабильности и маны во вражеской стране с приростом дипломатического веса для вас.\n       Мирный договор для захвата меркантилизма у соперника.\n       Мирный договор для принуждения врага к вступлению в вашу торговую лигу.\n       Мирный договор для захвата меркантилизма в торговых войнах.\n       Мирный договор для получения торгового влияния в домашнем торговом узле врага.\n       Мирный договор для уменьшения величия врага и получения престижа."
 pte_settings.62: "Разоружение армии"
 pte_settings.63: "Потребовать рабов-солдат"
 pte_settings.64: "Демилитаризовать границы"
 pte_settings.65: "Разоружение флота"
 pte_settings.66: "Остановить рабские набеги"
 
 pte_army_disarmament_enabled_tt: "Мирный договор §YРазоружения армии§! §Gвключён§!."
 pte_army_disarmament_disabled_tt: "Мирный договор §YРазоружения армии§! §Rотключён§!."
 pte_manpower_enabled_tt: "Мирный договор §YТребования рабов-солдат§! §Gвключён§!."
 pte_manpower_disabled_tt: "Мирный договор §YТребования рабов-солдат§! §Rотключён§!."
 pte_demil_border_enabled_tt: "Мирный договор §YДемилитаризации границ§! §Gвключён§!."
 pte_demil_border_disabled_tt: "Мирный договор §YДемилитаризации границ§! §Rотключён§!."
 pte_fleet_disarmament_enabled_tt: "Мирный договор §YРазоружения флота§! §Gвключён§!."
 pte_fleet_disarmament_disabled_tt: "Мирный договор §YРазоружения флота§! §Rотключён§!."
 pte_stop_raid_enabled_tt: "Мирный договор §YОстановки рабских набегов§! §Gвключён§!."
 pte_stop_raid_disabled_tt: "Мирный договор §YОстановки рабских набегов§! §Rотключён§!."
 
#tech and knowledge
 pte_settings.70: "Технологии и Институты"
 pte_settings.71: "Эта группа содержит:\n       Стандартные мирные договоры для кражи технологий у вражеского лидера в случае отставания от него на 2 уровня\n       Мирный договор для прироста прогресса института в вашей столичной области в случае, если этот институт принят врагом\n        CB Набег за знаниями, позволяющий красть технологии и институты дешевле."
 pte_settings.72: "Стандартный Принудительный обмен технологиями"
 pte_settings.73: "Принудительный обмен знаниями"
 pte_settings.74: "Набег за знаниями"
 
 pte_orig_tech_sharing_enabled_tt: "Мирный договор Стандартного §YПринудительного обмена технологиями§! §Gвключён§!."
 pte_orig_tech_sharing_disabled_tt: "Мирный договор Стандартного §YПринудительного обмена технологиями§! §Rотключён§!."
 pte_knowledge_sharing_enabled_tt: "Мирный договор §YПринудительного обмена знаниями§! §Gвключён§!."
 pte_knowledge_sharing_disabled_tt: "Мирный договор §YПринудительного обмена знаниями§! §Rотключён§!."
 pte_raid_knowledge_enabled_tt: "CB §YНабег за знаниями§! и все соответствующие мирные договоры §Gвключены§!."
 pte_raid_knowledge_disabled_tt: "CB §YНабег за знаниями§! и все соответствующие мирные договоры §Rотключены§!."
 
#ruler and advisors
 pte_settings.80: "Правитель и советники"
 pte_settings.81: "Эта группа содержит мирные договоры, позволяющие:\n       Снизить навык вражеского правителя и повысить ваш.\n       Убить вражеского правителя и получить ману, равную его навыкам x3.\n       Убить вражеского правителя и уменьшить ваш голод.\n       Похитить вражеского советника."
 pte_settings.82: "Потребовать управленческую помощь"
 pte_settings.83: "Потребовать сеппуку"
 pte_settings.84: "Съесть правителя"
 pte_settings.85: "Похитить советника"
 
 pte_aid_enabled_tt: "Мирные договоры §YТребования управленческой помощи§! §Gвключены§!."
 pte_aid_disabled_tt: "Мирные договоры §YТребования управленческой помощи§! §Rотключены§!."
 pte_seppuku_enabled_tt: "Мирный договор §YТребования сеппуку§! §Gвключён§!."
 pte_seppuku_disabled_tt: "Мирный договор §YТребования сеппуку§! §Rотключён§!."
 pte_sacrifice_enabled_tt: "Мирный договор §YПожирания правителя§! §Gвключён§!."
 pte_sacrifice_disabled_tt: "Мирный договор §YПожирания правителя§! §Rотключён§!."
 pte_advisor_enabled_tt: "Мирные договоры §YПохищения советника§! §Gвключены§!."
 pte_advisor_disabled_tt: "Мирные договоры §YПохищения советника§! §Rотключены§!."
 
#diplomacy
 pte_settings.90: "Дипломатия"
 pte_settings.91: "Эта группа содержит casus bellis, позволяющие:\n       Снизить стоимость §YОсвобождения вассала§!, §YОсвобождения держав§!, §YВозвращения национальных провинций§!, §YОтказа от национальных провинций§!.\n       Снизить стоимость военных мирных договоров и использовать §YПоказ силы§! против вражекого лидера.\n       Оба вышеуказанных эффекта, которые также могут быть использованы против против любого члена коалиции, направленной против вас.\n       Снизить стоимость §YТребования провинции§! и §YДемилитаризации границ§! при условии захвата исключительно §RПограничных§! провинций."
 pte_settings.92: "Освобождение"
 pte_settings.93: "Вмешаться в войну за независимость"
 pte_settings.94: "Разбить коалицию"
 pte_settings.95: "Пограничные трения"
 
 pte_liberation_enabled_tt: "Casus belli §YОсвобождение§! §Gвключён§!."
 pte_liberation_disabled_tt: "Casus belli §YОсвобождение§! §Rотключён§!."
 pte_rival_subject_enabled_tt: "Casus belli §YВмешаться в войну за независимость§! §Gвключён§!."
 pte_rival_subject_disabled_tt: "Casus belli §YВмешаться в войну за независимость§! §Rотключён§!."
 pte_anti_coalition_enabled_tt: "Casus belli §YРазбить коалицию§! §Gвключён§!."
 pte_anti_coalition_disabled_tt: "Casus belli §YРазбить коалицию§!  §Rотключён§!."
 pte_border_friction_enabled_tt: "Casus belli §YПограничные трения§! §Gвключён§!."
 pte_border_friction_disabled_tt: "Casus belli §YПограничные трения§! §Rотключён§!."
 
#dlc
 pte_mandate_of_heaven_tt: "§RОтсутствует ДЛС:§! §YМандат Небес§!"
 pte_emperor_tt: "§RОтсутствует ДЛС:§! §YИмператор§!"
 pte_el_dorado_tt: "§RОтсутствует ДЛС:§! §YЭль Дорадо§!"
 pte_rights_of_man_tt: "§RОтсутствует ДЛС:§! §YПрава Человека§!"
 pte_dlc_mare_nostrum_tt: "§RОтсутствует ДЛС:§! §YМаре Нострум§!"