l_english:
# __0 - title, ___1 - desc, others are options
# §G____§! - green text §R____§! - red text §Y____§! - yellow text

#decision:
 pte_game_options_title: "PTE Anbennar settings"
 pte_game_options_desc: ""

#general
 pte_settings.10: "PTE Anbennar settings"
 pte_settings.11: "Welcome to Peace Treaties Expanded Anbennar.\nHere you can turn on/off various casus bellis and/or peace treaties to your liking.\n\nEvent options will either enable/disable certain mechanic of mod, or open the settings menu of the mechanic group.\nTooltips will show you if mechanic is enabled or not."
 pte_settings.12: "Done, return me to the game"
 pte_settings.13: "Check and enable/disable all settings"
 pte_settings.14: "Decrease/increase mandate peace treaties"
 pte_settings.15: "Infernal Empire of Anbennar"
 pte_settings.16: "Share map peace treaties"
 
 pte_all_enabled_tt: "All mechanics of Peace Treaties Expanded Anbennar are §Genabled§!!\nClick to disable all."
 pte_all_disabled_tt: "All mechanics of Peace Treaties Expanded Anbennar are §Rdisabled§!!\nClick to enable all."
 pte_partially_enabled_tt: "Mechanics of Peace Treaties Expanded Anbennar are §Ypartially enabled§!!\nClick to disable all."
 pte_mandate_enabled_tt: "§YStrengthen/Crush the Mandate§! peace treaties are §Genabled§!."
 pte_mandate_disabled_tt: "§YStrengthen/Crush the Mandate§! peace treaties are §Rdisabled§!."
 pte_infernal_enabled_tt: "PTE's mechanic for conversion Empire of Anbennar to Infernal Court is §Genabled§!."
 pte_infernal_disabled_tt: "PTE's mechanic for conversion Empire of Anbennar to Infernal Court is §Rdisabled§!."
 pte_map_enabled_tt: "§YShare map§! peace treaties are §Genabled§!."
 pte_map_disabled_tt: "§YShare map§! peace treaties are §Rdisabled§!."
 
#dynastic
 pte_settings.20: "Dynasty"
 pte_settings.21: "This group contains:\n       Force divorce our ruler with consort from enemy country.\n       Force divorce enemy ruler with consort from our country.\n       Force royal marriage between us and enemy.\n       Deligitimize dynastic branch.\n       Demand dynastic legitimization."
 pte_settings.22: "Return to main mod menu"
 pte_settings.23: "Enforced divorces"
 pte_settings.24: "Enforced royal marriage"
 pte_settings.25: "Enforced (de-)legitimization"
 
 pte_divorce_enabled_tt: "§YForced Divorce§! peace treaties are §Genabled§!."
 pte_divorce_disabled_tt: "§YForced Divorce§! peace treaties are §Rdisabled§!."
 pte_marriage_enabled_tt: "§YEnforced Marriage§! peace treaty is §Genabled§!."
 pte_marriage_disabled_tt: "§YEnforced Marriage§! peace treaty is §Rdisabled§!."
 pte_legitimize_enabled_tt: "§YDemand Dynastic Legitimization§! and §YDeligitimize dynastic branch§! peace treaties are §Genabled§!."
 pte_legitimize_disabled_tt: "§YDemand Dynastic Legitimization§! and §YDeligitimize dynastic branch§! peace treaties are §Rdisabled§!."
 
#hegemony
 pte_settings.30: "Hegemony"
 pte_settings.31: "This group contains:\n       CBs for economy/naval/military hegemons and their unique peace treaties.\n       Peace treaty to make enemy give up cultural hegemony.\n       CB and peace treaty for taking over cultural hegemony of your cultural group held by enemy."
 pte_settings.32: "Economy hegemon"
 pte_settings.33: "Naval hegemon"
 pte_settings.34: "Military hegemon"
 pte_settings.35: "Give up cultural hegemony"
 pte_settings.36: "Take over cultural hegemony"
 pte_settings.37: "Nationalism for cultural hegemon"
 
 pte_ecoheg_enabled_tt: "§YEconomic Hegemony§! CB and §YForce bankruptcy§! peace treaty is §Genabled§!."
 pte_ecoheg_disabled_tt: "§YEconomic Hegemony§! CB and §YForce bankruptcy§! peace treaty is §Rdisabled§!."
 pte_navheg_enabled_tt: "§YNaval Hegemony§! CB and §YSeize Fleets§! peace treaty is §Genabled§!."
 pte_navheg_disabled_tt: "§YNaval Hegemony§! CB and §YSeize Fleets§! peace treaty is §Rdisabled§!."
 pte_milheg_enabled_tt: "§YMilitary Hegemony§! CB and §YDemonstrate Military Supremacy§! peace treaty is §Genabled§!."
 pte_milheg_disabled_tt: "§YMilitary Hegemony§! CB and §YDemonstrate Military Supremacy§! peace treaty is §Rdisabled§!."
 pte_culhegA_enabled_tt: "§YGive up Cultural Hegemony§! peace treaty is §Genabled§!."
 pte_culhegA_disabled_tt: "§YGive up Cultural Hegemony§! peace treaty is §Rdisabled§!."
 pte_culhegB_enabled_tt: "§YClaim Cultural Hegemony§! CB and §YClaim Cultural Hegemony§! peace treaty is §Genabled§!."
 pte_culhegB_disabled_tt: "§YClaim Cultural Hegemony§! CB and §YClaim Cultural Hegemony§! peace treaty is §Rdisabled§!."
 pte_culheg_nation_enabled_tt: "Modified §YNationalism§! CB for §YCultural Hegemon§! is §Genabled§!."
 pte_culheg_nation_disabled_tt: "Modified §YNationalism§! CB for §YCultural Hegemon§! is §Rdisabled§!."
 
#religious
 pte_settings.40: "Religion"
 pte_settings.41: "This group contains:\n       CB and peace treaty for lifting excommunication from your country.\n       Peace treaty for changing High Rector to your candidate.\n       Peace treaty for plundering High Rectorate treasury.\n       CB and peace treaty to slow down the enemy's conversion of the provinces of your faith to his faith.\n       Peace treaty to spawn custom center of reformation of your faith in enemy's capital.\n       Peace treaty to abduct enemy's veridical.\n       Peace treaty to seize the title of \"Defender of faith\"."
 pte_settings.42: "Lift Excommunication"
 pte_settings.43: "Install Antirector"
 pte_settings.44: "Plunder the Treasury of the Rectorate"
 pte_settings.45: "Protect Religious Bretheren"
 pte_settings.46: "Spread the True Faith"
 pte_settings.47: "Abduct Veridical"
 pte_settings.48: "Claim Defender of Faith"
 
 pte_excom_enabled_tt: "§YLift Excommunication§! peace treaty is §Genabled§!."
 pte_excom_disabled_tt: "§YLift Excommunication§! peace treaty is §Rdisabled§!."
 pte_antipope_enabled_tt: "§YInstall Antirector§! peace treaty is §Genabled§!."
 pte_antipope_disabled_tt: "§YInstall Antirector§! peace treaty is §Rdisabled§!."
 pte_curia_enabled_tt: "§YPlunder the Treasury of the Rectorate§! peace treaty is §Genabled§!."
 pte_curia_disabled_tt: "§YPlunder the Treasury of the Rectorate§! peace treaty is §Rdisabled§!."
 pte_bretheren_enabled_tt: "§YProtect Religious Bretheren§! CB and peace treaty are §Genabled§!."
 pte_bretheren_disabled_tt: "§YProtect Religious Bretheren§! CB and peace treaty are §Rdisabled§!."
 pte_spawncenter_enabled_tt: "§YSpread the True Faith§! peace treaty is §Genabled§!."
 pte_spawncenter_disabled_tt: "§YSpread the True Faith§! peace treaty is §Rdisabled§!."
 pte_cardinal_enabled_tt: "§YAbduct Veridical§! peace treaty is §Genabled§!."
 pte_cardinal_disabled_tt: "§YAbduct Veridical§! peace treaty is §Rdisabled§!."
 pte_dof_enabled_tt: "§YClaim Defender of Faith§! peace treaty is §Genabled§!."
 pte_dof_disabled_tt: "§YClaim Defender of Faith§! peace treaty is §Rdisabled§!."
 
#economy
 pte_settings.50: "Economy"
 pte_settings.51: "This group contains:\n       CB and peace treaty to ban slavery in enemy's country.\n       Peace treaty for decreasing stability and mana in enemy's country with gain power projection for you.\n       Peace treaty for seizing mercantilism from rival.\n       Peace treaty to force enemy join your trade league.\n       Peace treaty for seizing mercantilism in trade wars.\n       Peace treaty for getting trade influence in enemy's home trade node.\n       Peace treaty to decrease enemy's splendor and get prestige."
 pte_settings.52: "Ban Slavery"
 pte_settings.53: "Destabilize Nation"
 pte_settings.54: "Enforced Embargo"
 pte_settings.55: "Join Trade League"
 pte_settings.56: "Seize Mercantilism"
 pte_settings.57: "Unequal Treaty"
 pte_settings.58: "Raid Splendid Court"
 
 pte_ban_slave_enabled_tt: "§YBan Slavery§! CB and peace treaty are §Genabled§!."
 pte_ban_slave_disabled_tt: "§YBan Slavery§! CB and peace treaty are §Rdisabled§!."
 pte_destabilize_enabled_tt: "§YDestabilize Nation§! peace treaty is §Genabled§!."
 pte_destabilize_disabled_tt: "§YDestabilize Nation§! peace treaty is §Rdisabled§!."
 pte_embargo_enabled_tt: "§YEnforced Embargo§! peace treaty is §Genabled§!."
 pte_embargo_disabled_tt: "§YEnforced Embargo§! peace treaty is §Rdisabled§!."
 pte_trade_league_enabled_tt: "§YJoin Trade League§! peace treaty is §Genabled§!."
 pte_trade_league_disabled_tt: "§YJoin Trade League§! peace treaty is §Rdisabled§!."
 pte_mercantilism_enabled_tt: "§YSeize Mercantilism§! peace treaty is §Genabled§!."
 pte_mercantilism_disabled_tt: "§YSeize Mercantilism§! peace treaty is §Rdisabled§!."
 pte_unequal_treaty_enabled_tt: "§YUnequal Treaty§! peace treaty is §Genabled§!."
 pte_unequal_treaty_disabled_tt: "§YUnequal Treaty§! peace treaty is §Rdisabled§!."
 pte_raid_court_enabled_tt: "§YRaid Splendid Court§! peace treaty is §Genabled§!."
 pte_raid_court_disabled_tt: "§YRaid Splendid Court§! peace treaty is §Rdisabled§!."
 
#militare
 pte_settings.60: "Military"
 pte_settings.61: "This group contains peace treaties which will:\n       Peace treaty to put land army limit and regiment cost debuff on your enemy alongside with war exhaustion.\n       Peace treaty to steal manpower from your enemy at cost of prestige or army traditions.\n       Peace treaty to demolish all enemy's fortresses on your borders.\n       Peace treaty to put fleet limit and ship cost debuff on your enemy alongside with war exhaustion.\n       Peace treaty for protecting your coastal provinces from raiding."
 pte_settings.62: "Army Disarmament"
 pte_settings.63: "Demand Slave Soldiers"
 pte_settings.64: "Demilitarize Borders"
 pte_settings.65: "Fleet Disarmament"
 pte_settings.66: "Stop Slave Raids"
 
 pte_army_disarmament_enabled_tt: "§YArmy Disarmament§! peace treaty is §Genabled§!."
 pte_army_disarmament_disabled_tt: "§YArmy Disarmament§! peace treaty is §Rdisabled§!."
 pte_manpower_enabled_tt: "§YDemand Slave Soldiers§! peace treaty is §Genabled§!."
 pte_manpower_disabled_tt: "§YDemand Slave Soldiers§! peace treaty is §Rdisabled§!."
 pte_demil_border_enabled_tt: "§YDemilitarize Borders§! peace treaty is §Genabled§!."
 pte_demil_border_disabled_tt: "§YDemilitarize Borders§! peace treaty is §Rdisabled§!."
 pte_fleet_disarmament_enabled_tt: "§YFleet Disarmament§! peace treaty is §Genabled§!."
 pte_fleet_disarmament_disabled_tt: "§YFleet Disarmament§! peace treaty is §Rdisabled§!."
 pte_stop_raid_enabled_tt: "§YStop Slave Raids§! peace treaty is §Genabled§!."
 pte_stop_raid_disabled_tt: "§YStop Slave Raids§! peace treaty is §Rdisabled§!."
 
#tech and knowledge
 pte_settings.70: "Technology and Institutions"
 pte_settings.71: "This group contains:\n       Original PTE's peace treaties for stealing technology from enemy's leader if you you're 2 levels behind them\n       Peace treaty for gain institution progress in your capital area, if it's embraced by enemy.\n       Raid for Knowledge CB which allows cheaper stealing technologies and institution."
 pte_settings.72: "Original Force Technology Sharing"
 pte_settings.73: "Force Knowledge Sharing"
 pte_settings.74: "Raid for Knowledge"
 
 pte_orig_tech_sharing_enabled_tt: "General §YForce Technology Sharing§! peace treaty is §Genabled§!."
 pte_orig_tech_sharing_disabled_tt: "General §YForce Technology Sharing§! peace treaty is §Rdisabled§!."
 pte_knowledge_sharing_enabled_tt: "§YForce Knowledge Sharing§! peace treaty is §Genabled§!."
 pte_knowledge_sharing_disabled_tt: "§YForce Knowledge Sharing§! peace treaty is §Rdisabled§!."
 pte_raid_knowledge_enabled_tt: "§YRaid for Knowledge§! CB and all it's peace treaties are §Genabled§!."
 pte_raid_knowledge_disabled_tt: "§YRaid for Knowledge§! CB and all it's peace treaties are §Rdisabled§!."
 
#ruler and advisors
 pte_settings.80: "Ruler and advisors"
 pte_settings.81: "This group contains peace treaties which will:\n       Decrease enemy's ruler's skill and increase your.\n       Kill enemy's ruler and get mana equal to their skills x3.\n       Kill enemy's ruler and decrease your hunger.\n       Take enemy's advisor."
 pte_settings.82: "Demand Skill Aides"
 pte_settings.83: "Force Seppuku"
 pte_settings.84: "Sacrifice Ruler"
 pte_settings.85: "Abduct Advisor"
 
 pte_aid_enabled_tt: "§YDemand Skill Aides§! peace treaties are §Genabled§!."
 pte_aid_disabled_tt: "§YDemand Skill Aides§! peace treaties are §Rdisabled§!."
 pte_seppuku_enabled_tt: "§YForce Seppuku§! peace treaty is §Genabled§!."
 pte_seppuku_disabled_tt: "§YForce Seppuku§! peace treaty is §Rdisabled§!."
 pte_sacrifice_enabled_tt: "§YSacrifice Ruler§! peace treaty is §Genabled§!."
 pte_sacrifice_disabled_tt: "§YSacrifice Ruler§! peace treaty is §Rdisabled§!."
 pte_advisor_enabled_tt: "§YAbduct Advisor§! peace treaties are §Genabled§!."
 pte_advisor_disabled_tt: "§YAbduct Advisor§! peace treaties are §Rdisabled§!."
 
#diplomacy
 pte_settings.90: "Diplomacy"
 pte_settings.91: "This group contains casus bellis which will:\n       Decrease cost of §YReleasing Nations§! from enemy, §YReturn Cores§!, §YRevoke Cores§!.\n       Decrease cost of military peace treaties and use §YShow Strength§! against enemy leader.\n       Both of upper effects + can be used against any member of coalition targeting you.\n       Decrease cost of §YDemand Province§! and §YDemilitarize borders§! but you can only take §RBorder§! provinces."
 pte_settings.92: "Liberation"
 pte_settings.93: "Intervene in Independence War"
 pte_settings.94: "Crush the Coalition"
 pte_settings.95: "Border Friction"
 
 pte_liberation_enabled_tt: "§YLiberation§! casus belli is §Genabled§!."
 pte_liberation_disabled_tt: "§YLiberation§! casus belli is §Rdisabled§!."
 pte_rival_subject_enabled_tt: "§YIntervene in Independence War§! casus belli is §Genabled§!."
 pte_rival_subject_disabled_tt: "§YIntervene in Independence War§! casus belli is §Rdisabled§!."
 pte_anti_coalition_enabled_tt: "§YCrush the Coalition§! casus belli is §Genabled§!."
 pte_anti_coalition_disabled_tt: "§YCrush the Coalition§! casus belli is §Rdisabled§!."
 pte_border_friction_enabled_tt: "§YBorder Friction§! casus belli is §Genabled§!."
 pte_border_friction_disabled_tt: "§YBorder Friction§! casus belli is §Rdisabled§!."
 
#dlc
 pte_mandate_of_heaven_tt: "§RMissing DLC:§! §YMandate of Heaven§!"
 pte_emperor_tt: "§RMissing DLC:§! §YEmperor§!"
 pte_el_dorado_tt: "§RMissing DLC:§! §YEl Dorado§!"
 pte_rights_of_man_tt: "§RMissing DLC:§! §YRights of Man§!"
 pte_dlc_mare_nostrum_tt: "§RMissing DLC:§! §YMare Nostrum§!"